name: Bandit Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    name: Run Bandit Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bandit Scan
        uses: shundor/bandit-action@v1
        with:
          path: "."
          level: high                # Report only high-severity issues
          confidence: high           # Report only high-confidence issues
          exit_zero: true            # Exit with 0 to avoid pipeline failure
